local_backend: true
backend:
#github
  name: github
  repo: "moto42/etgra-erzgebirge" 
  branch: main


#  Where are uploads in the repo?
media_folder: "src/_static/images/uploads"
# Where are uploads in the live site?
public_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: pages
    delete: false
    editor:
      preview: false
    files: 
    - label: "Front Page"
      name: "home"
      file : "src/index.md"
      fields:
      - {label: "Title", name: "title", widget: "string"}
  - label: "Global Data"
    name: globaldata
    delete: false
    create: false
    editor:
      preview: false
    files: 
    - label: "Contact Info"
      name: "contactinfo"
      file : "src/_data/contactinfo.json"
      fields:
      - label: "phone"
        name: "phone"
        widget: "string"
        hint: "Primary Business Contact Number"
        pattern: ["[0-9]{3}-[0-9]{3}-[0-9]{4}", "Please enter phone number in ###-###-#### format"]
      - label: "Address Line One"
        name: "addr1"
        widget: "string"
      - label: "Address Line Two"
        name: "addr2"
        widget: "string"
      