local_backend: true
backend:
  # github
  name: github
  repo: "moto42/etgra-erzgebirge"
  branch: main

#  Where are uploads in the repo?
media_folder: "src/_static/images/uploads"
# Where are uploads in the live site?
public_folder: "/images/uploads"

collections:
  - label: "Primary Pages"
    name: "primarypages"
    files:
      - label: Front page
        name: frontpage
        file: /src/index.11tydata.json
        editor:
          preview: false
        fields:
          - label: "Hero Banner"
            name: "herobanner"
            widget: "list"
            hint: A rotating set of images and statements appearing at the top of the page.
            fields:
              - label: Statement
                name: statement
                widget: string
                hint: The statement to appear next to this banner
              - label: Banner
                name: image
                widget: image
                allow_multiple: false
                choose_url: false
                media_folder: /src/_static/images/uploads/frontpage
                public_folder: /images/uploads/frontpage
                hint: A banner image.
          - label: "Feature Cards"
            name: featurecards
            hint: "Cards with a horizontal layout, to callout features and services"
            widget: list
            fields:
              - label: Headline
                name: headline
                widget: string
                hint: Headline to appear at top of card
              - label: Body text
                name: blurb
                widget: string
                hint: The text to appear in the body of the card.
              - lable: Link
                name: link
                widget: string
                required: false
                hint: optional URL that this card should link too.
              - label: Icon
                name: icon
                widget: image
                allow_multiple: false
                choose_url: false
                media_folder: /src/_static/images/uploads/frontpage/cards
                public_folder: /images/uploads/frontpage/cards
                hint: Icon that will apear on this card.
              - label: Image Attribution
                name: imgattr
                widget: string
                required: false
                hint: url to image attribution, if required.
                pattern:
                  [
                    "^https?://",
                    "Please enter a url beginnign with 'http(s)://",
                  ]
          - label: Body
            name: content
            widget: list
            label_singular: "Section"
            hint: ""
            types:
              - label: "Text"
                name: "text"
                widget: object
                summary: "{{fields.text | truncate(40)}}"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: markdown
                    buttons:
                      - bold
                      - italic
                      - code
                      - link
                      - heading-two
                      - heading-three
                      - heading-four
                      - heading-five
                      - heading-six
                      - quote
                      - bulleted-list
                      - numbered-list
                    editor_components:
                      - image
              - label: "Banner"
                name: "banner"
                widget: object
                summary: "{{fields.heading}}"
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: string
                    hint: Heading to appear in the banner
                  - label: "Heading Level"
                    name: "headinglevel"
                    widget: select
                    options:
                      - "h2"
                      - "h3"
                      - "h4"
                      - "h5"
                      - "h6"
                    default: "h2"
                    hint: The level of the heading to appear in the banner
                  - label: "Image"
                    name: "image"
                    widget: image
                    allow_multiple: false
                    choose_url: false
                    media_folder: /src/_static/images/uploads/frontpage/banners
                    public_folder: /images/uploads/frontpage/banners
                    hint: Image to appear in the banner
  - label: "Content Pages"
    name: contentpages
    folder: "src/pages"
    delete: true
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: string
        required: true
      - label: body
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - quote
          - bulleted-list
          - numbered-list
        editor_components:
          - image
          - widget_banner
      # - label: "Content"
      #   name: "content"
      #   required: true
      #   widget: list
      #   label_singular: "Section"
      #   hint: ""
      #   types:
      #     - label: "Text"
      #       name: "text"
      #       widget: object
      #       summary: "{{fields.text | truncate(40)}}"
      #       fields:
      #         - label: "Text"
      #           name: "text"
      #           widget: markdown
      #           buttons:
      #             - bold
      #             - italic
      #             - code
      #             - link
      #             - heading-two
      #             - heading-three
      #             - heading-four
      #             - heading-five
      #             - heading-six
      #             - quote
      #             - bulleted-list
      #             - numbered-list
      #           editor_components:
      #             - image
      #     - label: "Banner"
      #       name: "banner"
      #       widget: object
      #       summary: "{{fields.heading}}"
      #       fields:
      #         - label: "Heading"
      #           name: "heading"
      #           widget: string
      #           hint: Heading to appear in the banner
      #         - label: "Heading Level"
      #           name: "headinglevel"
      #           widget: select
      #           options:
      #             - "h2"
      #             - "h3"
      #             - "h4"
      #             - "h5"
      #             - "h6"
      #           default: "h2"
      #           hint: The level of the heading to appear in the banner
      #         - label: "Image"
      #           name: "image"
      #           widget: image
      #           allow_multiple: false
      #           choose_url: false
      #           media_folder: /src/_static/images/uploads/contentpages/banners
      #           public_folder: /images/uploads/contentpages/banners
      #           hint: Image to appear in the banner
      - label: "Tags"
        name: "tags"
        widget: hidden
        default: ["contentpages"]
  - label: "Global Data"
    name: globaldata
    delete: false
    create: false
    editor:
      preview: false
    files:
      - label: "Contact Info"
        name: "contactinfo"
        file: "src/_data/contactinfo.json"
        fields:
          - label: "phone"
            name: "phone"
            widget: "string"
            hint: "Primary Business Contact Number"
            pattern:
              [
                "[0-9]{3}-[0-9]{3}-[0-9]{4}",
                "Please enter phone number in ###-###-#### format",
              ]
          - label: "Address Line One"
            name: "addr1"
            widget: "string"
          - label: "Address Line Two"
            name: "addr2"
            widget: "string"
      - label: "Header and Footer"
        name: "headerfooter"
        file: "src/_data/headerfooter.json"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "image"
            allow_multiple: false
            choose_url: false
            hint: The logotype that will appear in the header and footer of the page.
