local_backend: true
backend:
#github
  name: github
  repo: "moto42/etgra-erzgebirge" 
  branch: main


#  Where are uploads in the repo?
media_folder: "src/_static/images/uploads"
# Where are uploads in the live site?
public_folder: "/images/uploads"

collections:
  - label: "Primary Pages"
    name: "primarypages"
    files: 
      - label: Front page
        name: frontpage
        file: /src/index.11tydata.json
        editor:
          preview: false
        fields:
          - label: "Hero image"
            name: "heroimage"
            widget: "image"
            hint: Large banner image which appears at the top of the page.
            allow_multiple: false
            choose_url: false
            media_folder: frontpage
          - label: Body
            name: content
            widget: markdown
            hint: ""
      
  - label: "Content Pages"
    name: contentpages
    folder: "src/pages"
    delete: true
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: string
        required: true
      - label: "Content"
        name: "body"
        required: true
        widget: markdown
        buttons: 
          - bold
          - italic
          - code
          - link
          # - heading-one
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - quote
          - bulleted-list
          - numbered-list
        editor_components:
          - image
          # - code-block
      - label: "Tags"
        name: "tags"
        widget: hidden
        default: ["contentpages"]
  - label: "Global Data"
    name: globaldata
    delete: false
    create: false
    editor:
      preview: false
    files: 
    - label: "Contact Info"
      name: "contactinfo"
      file : "src/_data/contactinfo.json"
      fields:
      - label: "phone"
        name: "phone"
        widget: "string"
        hint: "Primary Business Contact Number"
        pattern: ["[0-9]{3}-[0-9]{3}-[0-9]{4}", "Please enter phone number in ###-###-#### format"]
      - label: "Address Line One"
        name: "addr1"
        widget: "string"
      - label: "Address Line Two"
        name: "addr2"
        widget: "string"
    - label: "Header and Footer"
      name: "headerfooter"
      file: "src/_data/headerfooter.json"
      fields:
        - label: "Logo"
          name: "logo"
          widget: "image"
          allow_multiple: false
          choose_url: false
          hint: The logotype that will appear in the header and footer of the page.
